# This rule is not used by the project elasticweb itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the elasticweb.com.jwzhou.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/managed-by: kustomize
  name: elasticweb-editor-role
rules:
- apiGroups:
  - elasticweb.com.jwzhou
  resources:
  - elasticwebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticweb.com.jwzhou
  resources:
  - elasticwebs/status
  verbs:
  - get
