# This rule is not used by the project elasticweb itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to elasticweb.com.jwzhou resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/managed-by: kustomize
  name: elasticweb-viewer-role
rules:
- apiGroups:
  - elasticweb.com.jwzhou
  resources:
  - elasticwebs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticweb.com.jwzhou
  resources:
  - elasticwebs/status
  verbs:
  - get
